apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis/
  - postgresql/
  - mongodb/
  - kafka/
  - istio/

commonLabels:
  app.kubernetes.io/part-of: book-store
  app.kubernetes.io/managed-by: kustomize 