apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: book-store-dev

bases:
- ../../base

patches:
- path: configmap-patch.yaml
- path: resource-limits-patch.yaml

commonLabels:
  environment: dev 